<?php

namespace Database\Seeders;

use App\Models\Subject;
use Illuminate\Database\Seeder;

class SubjectArabicNamesSeeder extends Seeder
{
    public function run()
    {
        $map = [
            // Egyptian Primary
            'Arabic'                         => 'اللغة العربية',
            'Mathematics'                    => 'الرياضيات',
            'Maths'                          => 'الرياضيات',
            'English'                        => 'اللغة الإنجليزية',
            'Social Studies'                 => 'الدراسات الاجتماعية',
            'Science'                        => 'العلوم',
            'Islamic Education'              => 'التربية الدينية الإسلامية',
            'Christian Education'            => 'التربية الدينية المسيحية',
            'Art Education'                  => 'التربية الفنية',
            'Music Education'                => 'التربية الموسيقية',
            'Physical Education'             => 'التربية الرياضية',
            'Educational Activities'         => 'الأنشطة التربوية',
            'Information and Communications Technology' => 'تكنولوجيا المعلومات والاتصالات',
            'Professional Skills'            => 'المهارات المهنية',
            'Values and Respect for Others'  => 'القيم واحترام الآخر',

            // Egyptian Preparatory (additions)
            'Chemistry'                      => 'الكيمياء',
            'Physics'                        => 'الفيزياء',
            'Biology'                        => 'الأحياء',

            // Egyptian Secondary
            'Integrated Science'             => 'العلوم المتكاملة',
            'Philosophy and Logic'           => 'الفلسفة والمنطق',
            'National Education'             => 'التربية الوطنية',
            'Philosophy'                     => 'الفلسفة',
            'Algebra'                        => 'الجبر',
            'Geometry'                       => 'الهندسة',
            'Calculus'                       => 'التفاضل والتكامل',
            'Statics'                        => 'الإستاتيكا',
            'Dynamics'                       => 'الديناميكا',
            'Psychology and Sociology'       => 'علم النفس والاجتماع',
            'History'                        => 'التاريخ',
            'Geography'                      => 'الجغرافيا',
            'Psychology'                     => 'علم النفس',
            'Sociology'                      => 'علم الاجتماع',

            // Core Academic
            'Academic Writing'               => 'الكتابة الأكاديمية',
            'Literature'                     => 'الأدب',
            'Arabic Literature'              => 'الأدب العربي',
            'English Literature'             => 'الأدب الإنجليزي',
            'Comparative Literature'         => 'الأدب المقارن',
            'Creative Writing'               => 'الكتابة الإبداعية',
            'Linguistics'                    => 'علم اللغة',
            'Translation'                    => 'الترجمة',
            'Communication Skills'           => 'مهارات التواصل',
            'IELTS'                          => 'IELTS',
            'Statistics'                     => 'الإحصاء',
            'Logic'                          => 'المنطق',

            // Languages
            'French'                         => 'اللغة الفرنسية',
            'German'                         => 'اللغة الألمانية',
            'Italian'                        => 'اللغة الإيطالية',
            'Spanish'                        => 'اللغة الإسبانية',

            // Computer Science & IT
            'Computer Science'               => 'علوم الحاسب',
            'Information Technology'         => 'تكنولوجيا المعلومات',
            'Programming'                    => 'البرمجة',
            'Algorithm & Data Structures'    => 'الخوارزميات وهياكل البيانات',
            'C/C++'                          => 'C/C++',
            'C#'                             => 'C#',
            'JAVA'                           => 'جافا',
            'Python'                         => 'بايثون',
            'PHP'                            => 'PHP',
            'HTML'                           => 'HTML',
            'Jquery and JavaScript'          => 'جيكويري وجافاسكريبت',
            '.net'                           => '.NET',
            'Web Development'                => 'تطوير الويب',
            'Mobile App Development'         => 'تطوير تطبيقات الجوال',
            'DBMS'                           => 'قواعد البيانات',
            'Database Management'            => 'إدارة قواعد البيانات',
            'Computer networking'            => 'شبكات الحاسب',
            'Network Security'               => 'أمن الشبكات',
            'Cybersecurity'                  => 'الأمن السيبراني',
            'Operating Systems'              => 'أنظمة التشغيل',
            'Data Science'                   => 'علم البيانات',
            'Artificial Intelligence'        => 'الذكاء الاصطناعي',
            'Machine Learning'               => 'التعلم الآلي',
            'Deep Learning'                  => 'التعلم العميق',
            'Data Mining'                    => 'التنقيب في البيانات',
            'Big Data'                       => 'البيانات الضخمة',
            'Cloud Computing'                => 'الحوسبة السحابية',
            'DevOps'                         => 'DevOps',
            'Blockchain'                     => 'سلسلة الكتل',
            'Internet of Things'             => 'إنترنت الأشياء',
            'Virtual Reality'                => 'الواقع الافتراضي',
            'Augmented Reality'              => 'الواقع المعزز',
            'Computer Graphics'              => 'رسوميات الحاسب',
            'Animation'                      => 'الرسوم المتحركة',
            'Game Design'                    => 'تصميم الألعاب',
            'Natural Language Processing'    => 'معالجة اللغة الطبيعية',
            'Computer Vision'                => 'رؤية الحاسب',
            'Robotics'                       => 'الروبوتات',
            'Software Engineering'           => 'هندسة البرمجيات',
            'Information and Communications Technology' => 'تكنولوجيا المعلومات والاتصالات',

            // Engineering
            'Engineering Mechanics'          => 'ميكانيكا الهندسة',
            'Civil Engineering'              => 'الهندسة المدنية',
            'Electrical Engineering'         => 'الهندسة الكهربائية',
            'Mechanical'                     => 'الهندسة الميكانيكية',
            'Chemical Engineering'           => 'الهندسة الكيميائية',
            'Biomedical Engineering'         => 'الهندسة الطبية',
            'Industrial Engineering'         => 'الهندسة الصناعية',
            'Computer Engineering'           => 'هندسة الحاسب',
            'Aerospace Engineering'          => 'هندسة الطيران',
            'Petroleum Engineering'          => 'هندسة البترول',
            'Nuclear Engineering'            => 'الهندسة النووية',
            'Architecture'                   => 'الهندسة المعمارية',
            'Architectural Engineering'      => 'الهندسة المعمارية',
            'Environmental Engineering'      => 'الهندسة البيئية',
            'Marine Engineering'             => 'الهندسة البحرية',
            'Textile Engineering'            => 'هندسة النسيج',
            'Metallurgical Engineering'      => 'هندسة الفلزات',
            'Geological Engineering'         => 'الهندسة الجيولوجية',
            'Ceramic Engineering'            => 'هندسة السيراميك',
            'Agricultural Engineering'       => 'الهندسة الزراعية',
            'Structural Engineering'         => 'الهندسة الإنشائية',
            'Geotechnical Engineering'       => 'هندسة التربة والأساسات',
            'Transportation Engineering'     => 'هندسة النقل',
            'Materials Science'              => 'علم المواد',
            'Signal Processing'              => 'معالجة الإشارات',
            'Embedded Systems'               => 'الأنظمة المدمجة',
            'Power Systems'                  => 'نظم القوى الكهربائية',
            'Machine Design'                 => 'تصميم الآلات',
            'Mechatronics'                   => 'الميكاترونكس',
            'Engineering Physics'            => 'فيزياء هندسية',
            'Engineering Chemistry'          => 'كيمياء هندسية',
            'Surveying'                      => 'المساحة',
            'Construction Management'        => 'إدارة التشييد',
            'Control Systems'                => 'أنظمة التحكم',
            'Analog Electronics'             => 'الإلكترونيات التناظرية',
            'Digital Electronics'            => 'الإلكترونيات الرقمية',
            'Basic Electronics'              => 'أساسيات الإلكترونيات',
            'AutoCAD'                        => 'أوتوكاد',
            'Strength of Materials'          => 'مقاومة المواد',
            'Thermodynamics'                 => 'الديناميكا الحرارية',
            'Fluid Mechanics'                => 'ميكانيكا الموائع',
            'هندسة فراغية'                  => 'هندسة فراغية',

            // Basic Sciences
            'BioChemistry'                   => 'الكيمياء الحيوية',
            'Organic Chemistry'              => 'الكيمياء العضوية',
            'Inorganic Chemistry'            => 'الكيمياء غير العضوية',
            'Physical Chemistry'             => 'الكيمياء الفيزيائية',
            'Analytical Chemistry'           => 'الكيمياء التحليلية',
            'Biotechnology'                  => 'التقنية الحيوية',
            'Microbiology'                   => 'علم الأحياء الدقيقة',
            'Cell Biology'                   => 'بيولوجيا الخلية',
            'Molecular Biology'              => 'البيولوجيا الجزيئية',
            'Genetics'                       => 'علم الوراثة',
            'Immunology'                     => 'علم المناعة',
            'Neuroscience'                   => 'علم الأعصاب',
            'Astrophysics'                   => 'الفيزياء الفلكية',
            'Quantum Mechanics'              => 'ميكانيكا الكم',
            'Ecology'                        => 'علم البيئة',
            'Marine Biology'                 => 'الأحياء البحرية',
            'Geology'                        => 'علم الجيولوجيا',
            'Astronomy'                      => 'علم الفلك',
            'Meteorology'                    => 'علم الأرصاد الجوية',
            'Oceanography'                   => 'علم المحيطات',
            'Botany'                         => 'علم النبات',
            'Zoology'                        => 'علم الحيوان',
            'Virology'                       => 'علم الفيروسات',
            'Paleontology'                   => 'علم الحفريات',
            'Seismology'                     => 'علم الزلازل',
            'Hydrology'                      => 'علم المياه',
            'Environmental Science'          => 'العلوم البيئية',

            // Medicine
            'Anatomy'                        => 'علم التشريح',
            'Physiology'                     => 'علم وظائف الأعضاء',
            'Pathology'                      => 'علم الأمراض',
            'Pharmacology'                   => 'علم الأدوية',
            'Histology'                      => 'علم الأنسجة',
            'Cardiology'                     => 'أمراض القلب',
            'Dermatology'                    => 'الأمراض الجلدية',
            'Pediatrics'                     => 'طب الأطفال',
            'Internal Medicine'              => 'الباطنة',
            'Surgery'                        => 'الجراحة',
            'Obstetrics and Gynecology'      => 'أمراض النساء والتوليد',
            'Ophthalmology'                  => 'طب العيون',
            'Orthopedics'                    => 'جراحة العظام',
            'Psychiatry'                     => 'الطب النفسي',
            'Radiology'                      => 'الأشعة',
            'Anesthesiology'                 => 'التخدير',
            'Emergency Medicine'             => 'طب الطوارئ',
            'Public Health'                  => 'الصحة العامة',
            'Epidemiology'                   => 'علم الأوبئة',
            'Nursing'                        => 'التمريض',
            'Pharmacy'                       => 'الصيدلة',
            'Dentistry'                      => 'طب الأسنان',
            'Veterinary Medicine'            => 'الطب البيطري',
            'Nutrition'                      => 'علم التغذية',
            'Dietetics'                      => 'علم التغذية العلاجية',
            'Speech Therapy'                 => 'علاج النطق',
            'Occupational Therapy'           => 'العلاج الوظيفي',
            'Physical Therapy'               => 'العلاج الطبيعي',
            'Medical Laboratory Science'     => 'علوم المختبرات الطبية',
            'Health Administration'          => 'الإدارة الصحية',

            // Business
            'Accountancy'                    => 'المحاسبة',
            'Commerce'                       => 'التجارة',
            'Business Management'            => 'إدارة الأعمال',
            'Financial Management'           => 'الإدارة المالية',
            'Marketing'                      => 'التسويق',
            'Human Resources'                => 'الموارد البشرية',
            'Entrepreneurship'               => 'ريادة الأعمال',
            'Supply Chain Management'        => 'إدارة سلسلة التوريد',
            'International Business'         => 'الأعمال الدولية',
            'Business Ethics'                => 'أخلاقيات الأعمال',
            'Corporate Finance'              => 'التمويل المؤسسي',
            'Investment Management'          => 'إدارة الاستثمار',
            'Auditing'                       => 'المراجعة',
            'Business Law'                   => 'قانون الأعمال',
            'Organizational Behavior'        => 'السلوك التنظيمي',
            'Strategic Management'           => 'الإدارة الاستراتيجية',
            'Operations Management'          => 'إدارة العمليات',
            'E-Commerce'                     => 'التجارة الإلكترونية',
            'Real Estate'                    => 'العقارات',
            'Insurance'                      => 'التأمين',
            'Banking and Finance'            => 'البنوك والتمويل',
            'Income Tax'                     => 'ضريبة الدخل',
            'Company Law'                    => 'قانون الشركات',
            'Economics'                      => 'الاقتصاد',

            // Arts
            'Art and Craft'                  => 'الفنون والحرف',
            'Fine Arts'                      => 'الفنون الجميلة',
            'Graphic Design'                 => 'التصميم الجرافيكي',
            'Interior Design'                => 'التصميم الداخلي',
            'Fashion Design'                 => 'تصميم الأزياء',
            'Photography'                    => 'التصوير الفوتوغرافي',
            'Film Studies'                   => 'الدراسات السينمائية',
            'Theater Arts'                   => 'الفنون المسرحية',
            'Dance'                          => 'الرقص',
            'Music'                          => 'الموسيقى',
            'Adobe Photoshop'                => 'أدوبي فوتوشوب',
            'Digital Media'                  => 'الإعلام الرقمي',
            'Media Studies'                  => 'الدراسات الإعلامية',
            'Journalism'                     => 'الصحافة',

            // Social Sciences
            'Political Science'              => 'العلوم السياسية',
            'Social Work'                    => 'الخدمة الاجتماعية',
            'Criminology'                    => 'علم الجريمة',
            'International Relations'        => 'العلاقات الدولية',
            'Diplomacy'                      => 'الدبلوماسية',
            'Development Studies'            => 'دراسات التنمية',
            'Gender Studies'                 => 'دراسات النوع الاجتماعي',
            'Peace and Conflict Studies'     => 'دراسات السلام والصراع',
            'Urban Planning'                 => 'التخطيط العمراني',
            'Demography'                     => 'التركيبة السكانية',
            'Cultural Studies'               => 'الدراسات الثقافية',
            'Anthropology'                   => 'علم الإنسان',
            'Archaeology'                    => 'علم الآثار',

            // Law
            'Law'                            => 'القانون',
            'Constitutional Law'             => 'القانون الدستوري',
            'Criminal Law'                   => 'القانون الجنائي',
            'Civil Law'                      => 'القانون المدني',
            'International Law'              => 'القانون الدولي',
            'Human Rights Law'               => 'قانون حقوق الإنسان',
            'Environmental Law'              => 'قانون البيئة',
            'Tax Law'                        => 'قانون الضرائب',
            'Intellectual Property Law'      => 'قانون الملكية الفكرية',

            // Education
            'Education'                      => 'التربية',
            'Early Childhood Education'      => 'تربية الطفولة المبكرة',
            'Special Education'              => 'التربية الخاصة',
            'Educational Psychology'         => 'علم النفس التربوي',
            'Curriculum Development'         => 'تطوير المناهج',
            'Teaching Methods'               => 'طرق التدريس',
            'Education Technology'           => 'تكنولوجيا التعليم',
            'Educational Administration'     => 'الإدارة التعليمية',

            // Military & Security
            'Military Science'               => 'العلوم العسكرية',
            'Security Studies'               => 'الدراسات الأمنية',
            'Forensic Science'               => 'الطب الشرعي',
            'Fire Safety Engineering'        => 'هندسة السلامة من الحرائق',

            // Sports
            'Sports Science'                 => 'علوم الرياضة',
            'Coaching'                       => 'التدريب الرياضي',
            'Sports Management'              => 'الإدارة الرياضية',

            // Tools & Skills
            'Selenium Webdriver'             => 'سيلينيوم ويب درايفر',
            'R'                              => 'R',
            'HTML'                           => 'HTML',
            'PHP'                            => 'PHP',
            'CSS'                            => 'CSS',
            'Library Science'                => 'علم المكتبات',
            'Research Methods'               => 'طرق البحث',
            'Assignment Help'                => 'مساعدة في الواجبات',
            'Exam Help'                      => 'مساعدة في الامتحانات',
            'Project Help'                   => 'مساعدة في المشاريع',
        ];

        $count = 0;
        foreach ($map as $english => $arabic) {
            $subject = Subject::where('name', $english)->first();
            if ($subject && !$subject->name_ar) {
                $subject->update(['name_ar' => $arabic]);
                $count++;
            }
        }

        $this->command->info("Updated {$count} subjects with Arabic names.");
    }
}
