<?php

namespace Database\Seeders;

use App\Models\Subject;
use App\Models\SubjectSearchTerm;
use Illuminate\Database\Seeder;

class SubjectSearchTermsSeeder extends Seeder
{
    public function run()
    {
        // Map of search terms → subject names
        // Multiple terms can map to the same subject
        $map = [
            'math'    => ['Mathematics', 'Maths', 'Algebra', 'Geometry', 'Calculus', 'Statistics', 'Trigonometry', 'Applied Mathematics'],
            'maths'   => ['Mathematics', 'Maths'],
            'رياضيات' => ['Mathematics', 'Maths', 'Algebra', 'Geometry', 'Calculus', 'Statistics'],
            'حساب'    => ['Mathematics', 'Maths', 'Algebra', 'Calculus'],
            'algebra' => ['Algebra', 'Mathematics', 'Maths'],
            'calculus' => ['Calculus', 'Mathematics', 'Maths'],
            'trigonometry' => ['Calculus', 'Geometry', 'Mathematics'],
            'physics'  => ['Physics', 'Engineering Physics', 'Astrophysics', 'Quantum Mechanics', 'Nuclear Engineering'],
            'physic'  => ['Physics', 'Engineering Physics', 'Astrophysics'],
            'فيزياء'  => ['Physics', 'Engineering Physics', 'Quantum Mechanics'],
            'chemistry' => ['Chemistry', 'Organic Chemistry', 'Inorganic Chemistry', 'Physical Chemistry', 'Analytical Chemistry', 'BioChemistry'],
            'chem'    => ['Chemistry', 'Organic Chemistry', 'Inorganic Chemistry', 'BioChemistry'],
            'كيمياء'  => ['Chemistry', 'Organic Chemistry', 'Inorganic Chemistry', 'BioChemistry'],
            'biology'  => ['Biology', 'BioChemistry', 'Microbiology', 'Cell Biology', 'Molecular Biology', 'Marine Biology', 'Botany', 'Zoology'],
            'bio'     => ['Biology', 'Biotechnology', 'BioChemistry', 'Microbiology', 'Cell Biology', 'Molecular Biology'],
            'بيولوجيا' => ['Biology', 'Microbiology', 'Cell Biology', 'Molecular Biology'],
            'أحياء'    => ['Biology', 'Zoology', 'Botany'],
            'english'  => ['English', 'English Literature', 'IELTS', 'Linguistics', 'Communication Skills'],
            'إنجليزية' => ['English', 'English Literature', 'IELTS'],
            'لغة'     => ['English', 'Arabic', 'French', 'German', 'Linguistics'],
            'programming' => ['Programming', 'C/C++', 'C#', 'JAVA', 'Python', 'PHP', 'Web Development', 'Mobile App Development'],
            'programming language' => ['Programming', 'C/C++', 'C#', 'JAVA', 'Python', 'PHP', 'JavaScript'],
            'code'    => ['Programming', 'C/C++', 'C#', 'JAVA', 'Python', 'PHP', 'Web Development'],
            'برمجة'   => ['Programming', 'C/C++', 'JAVA', 'Python', 'PHP'],
            'python'  => ['Python', 'Programming', 'Machine Learning', 'Data Science', 'Artificial Intelligence'],
            'java'    => ['JAVA', 'Programming', 'Mobile App Development'],
            'javascript' => ['Jquery and JavaScript', 'Web Development', 'Programming'],
            'js'      => ['Jquery and JavaScript', 'Web Development'],
            'html'    => ['HTML', 'Web Development'],
            'css'     => ['Web Development', 'HTML', 'Computer Graphics'],
            'php'     => ['PHP', 'Web Development', 'Programming'],
            'database' => ['DBMS', 'Database Management', 'Computer Science'],
            'sql'     => ['DBMS', 'Database Management', 'Data Science'],
            'data'    => ['Data Science', 'Database Management', 'Data Mining', 'Big Data', 'Statistics'],
            'ai'      => ['Artificial Intelligence', 'Machine Learning', 'Deep Learning', 'Data Science', 'Robotics'],
            'ذكاء'    => ['Artificial Intelligence', 'Machine Learning', 'Robotics'],
            'machine learning' => ['Machine Learning', 'Artificial Intelligence', 'Deep Learning', 'Data Science'],
            'ml'      => ['Machine Learning', 'Artificial Intelligence', 'Data Science'],
            'network' => ['Computer networking', 'Network Security', 'Cybersecurity', 'Information Technology'],
            'networking' => ['Computer networking', 'Network Security'],
            'security' => ['Cybersecurity', 'Network Security', 'Information Technology'],
            'cyber'   => ['Cybersecurity', 'Network Security'],
            'accounting' => ['Accountancy', 'Financial Management', 'Auditing', 'Corporate Finance'],
            'account' => ['Accountancy', 'Financial Management', 'Income Tax', 'Tax Law', 'Auditing'],
            'finance' => ['Financial Management', 'Corporate Finance', 'Investment Management', 'Banking and Finance', 'Economics'],
            'business' => ['Business Management', 'Commerce', 'International Business', 'E-Commerce', 'Entrepreneurship'],
            'marketing' => ['Marketing', 'E-Commerce', 'Business Management', 'Digital Media'],
            'management' => ['Business Management', 'Operations Management', 'Strategic Management', 'Supply Chain Management', 'Human Resources'],
            'hr'      => ['Human Resources', 'Organizational Behavior', 'Business Management'],
            'engineering' => ['Engineering Mechanics', 'Civil Engineering', 'Electrical Engineering', 'Mechanical', 'Chemical Engineering', 'Software Engineering', 'Biomedical Engineering'],
            'هندسة'   => ['Engineering Mechanics', 'Civil Engineering', 'Electrical Engineering', 'Mechanical', 'هندسة فراغية', 'Architecture'],
            'civil'   => ['Civil Engineering', 'Structural Engineering', 'Geotechnical Engineering', 'Transportation Engineering', 'Construction Management'],
            'mechanical' => ['Mechanical', 'Machine Design', 'Thermodynamics', 'Fluid Mechanics', 'Strength of Materials', 'Mechatronics', 'Robotics'],
            'electrical' => ['Electrical Engineering', 'Power Systems', 'Control Systems', 'Embedded Systems', 'Signal Processing', 'Digital Electronics'],
            'electronics' => ['Basic Electronics', 'Analog Electronics', 'Digital Electronics', 'Embedded Systems', 'Electrical Engineering'],
            'circuit' => ['Analog Electronics', 'Basic Electronics', 'Digital Electronics', 'Electrical Engineering'],
            'signal'  => ['Signal Processing', 'Analog Electronics', 'Digital Electronics'],
            'medicine' => ['Internal Medicine', 'Emergency Medicine', 'Surgery', 'Pediatrics', 'Cardiology', 'Public Health'],
            'طب'      => ['Internal Medicine', 'Surgery', 'Pediatrics', 'Anatomy', 'Physiology', 'Pharmacology'],
            'anatomy' => ['Anatomy', 'Physiology', 'Medicine'],
            'surgery' => ['Surgery', 'Medicine', 'Anesthesiology'],
            'pharmacy' => ['Pharmacy', 'Pharmacology', 'Chemistry', 'BioChemistry'],
            'صيدلة'   => ['Pharmacy', 'Pharmacology'],
            'dentistry' => ['Dentistry', 'Anatomy'],
            'nursing' => ['Nursing', 'Public Health', 'Health Administration'],
            'تمريض'   => ['Nursing', 'Public Health'],
            'psychology' => ['Psychology', 'Psychology and Sociology', 'Psychiatry', 'Educational Psychology', 'Organizational Behavior'],
            'علم نفس' => ['Psychology', 'Psychiatry', 'Psychology and Sociology'],
            'sociology' => ['Sociology', 'Psychology and Sociology', 'Social Work', 'Cultural Studies'],
            'history'  => ['History', 'Archaeology', 'Political Science'],
            'تاريخ'   => ['History', 'Archaeology'],
            'geography' => ['Geography', 'Geology', 'Demography', 'Urban Planning'],
            'جغرافيا' => ['Geography', 'Geology', 'Urban Planning'],
            'arabic'   => ['Arabic', 'Arabic Literature', 'Islamic Education', 'Translation'],
            'عربي'    => ['Arabic', 'Arabic Literature', 'Translation'],
            'french'   => ['French', 'Translation', 'Linguistics'],
            'فرنسية'  => ['French', 'Translation'],
            'german'   => ['German', 'Translation', 'Linguistics'],
            'ألمانية' => ['German', 'Translation'],
            'philosophy' => ['Philosophy', 'Philosophy and Logic', 'Ethics'],
            'فلسفة'   => ['Philosophy', 'Philosophy and Logic'],
            'law'      => ['Law', 'Business Law', 'Constitutional Law', 'Criminal Law', 'Civil Law', 'International Law', 'Company Law'],
            'قانون'   => ['Law', 'Business Law', 'Company Law', 'International Law'],
            'media'    => ['Media Studies', 'Journalism', 'Digital Media', 'Film Studies', 'Photography'],
            'journalism' => ['Journalism', 'Media Studies', 'Creative Writing', 'Communication Skills'],
            'art'      => ['Art and Craft', 'Fine Arts', 'Art Education', 'Graphic Design', 'Animation', 'Photography'],
            'فن'      => ['Art and Craft', 'Fine Arts', 'Art Education', 'Graphic Design'],
            'design'   => ['Graphic Design', 'Interior Design', 'Fashion Design', 'Industrial Design', 'Adobe Photoshop', 'AutoCAD'],
            'تصميم'   => ['Graphic Design', 'Interior Design', 'Fashion Design', 'Architecture', 'AutoCAD'],
            'music'    => ['Music', 'Music Education', 'Theater Arts'],
            'موسيقى'  => ['Music', 'Music Education'],
            'sport'    => ['Physical Education', 'Sports Science', 'Coaching', 'Sports Management'],
            'رياضة'   => ['Physical Education', 'Sports Science', 'Coaching'],
            'education' => ['Education', 'Early Childhood Education', 'Special Education', 'Teaching Methods', 'Educational Psychology'],
            'تربية'   => ['Education', 'Early Childhood Education', 'Special Education', 'Teaching Methods', 'Educational Technology'],
            'computer' => ['Computer Science', 'Information Technology', 'Computer Engineering', 'Computer networking'],
            'software' => ['Software Engineering', 'Computer Science', 'Programming', 'Web Development'],
            'web'      => ['Web Development', 'HTML', 'PHP', 'JavaScript', 'Information Technology'],
            'mobile'   => ['Mobile App Development', 'Programming', 'Information Technology'],
            'app'      => ['Mobile App Development', 'Programming', 'Software Engineering'],
            'cloud'    => ['Cloud Computing', 'DevOps', 'Information Technology', 'Computer networking'],
            'data science' => ['Data Science', 'Statistics', 'Machine Learning', 'Big Data', 'Data Mining', 'Python'],
            'statistics' => ['Statistics', 'Data Science', 'Mathematics', 'Maths'],
            'إحصاء'   => ['Statistics', 'Data Science', 'Mathematics'],
            'economics' => ['Economics', 'Financial Management', 'Managerial Economics', 'Banking and Finance'],
            'اقتصاد'  => ['Economics', 'Financial Management', 'Banking and Finance'],
            'biology'  => ['Biology', 'Biotechnology', 'BioChemistry', 'Microbiology', 'Genetics', 'Cell Biology', 'Zoology'],
            'biotech' => ['Biotechnology', 'Biology', 'BioChemistry', 'Molecular Biology'],
            'chemistry' => ['Chemistry', 'Chemical Engineering', 'BioChemistry'],
            'geology'  => ['Geology', 'Geography', 'Earth Science', 'Paleontology', 'Seismology'],
            'astronomy' => ['Astronomy', 'Astrophysics', 'Physics', 'Space Science'],
            'logic'    => ['Philosophy and Logic', 'Philosophy', 'Algorithm & Data Structures', 'Computer Science'],
            'ethics'   => ['Business Ethics', 'Philosophy', 'Values and Respect for Others', 'Islamic Education'],
            'islamic'  => ['Islamic Education', 'Arabic', 'Arabic Literature'],
            'إسلامي'  => ['Islamic Education', 'Arabic'],
            'christian' => ['Christian Education'],
            'drawing'  => ['Art and Craft', 'Fine Arts', 'Art Education', 'AutoCAD', 'Adobe Photoshop'],
            'رسم'     => ['Art and Craft', 'Fine Arts', 'Art Education', 'Graphic Design'],
            'typing'   => ['Information Technology', 'Information and Communications Technology'],
            'ict'     => ['Information and Communications Technology', 'Information Technology', 'Computer Science'],
            'technology' => ['Information Technology', 'Information and Communications Technology', 'Educational Technology', 'Computer Science'],
            'robotics' => ['Robotics', 'Mechatronics', 'Control Systems', 'Artificial Intelligence'],
            'automation' => ['Control Systems', 'Robotics', 'Industrial Engineering'],
            'thermodynamics' => ['Thermodynamics', 'Mechanical', 'Chemical Engineering', 'Physics'],
            'mechanics' => ['Engineering Mechanics', 'Fluid Mechanics', 'Strength of Materials', 'Mechanical', 'Physics'],
            'architecture' => ['Architecture', 'Architectural Engineering', 'Interior Design', 'Urban Planning', 'AutoCAD'],
            'عمارة'   => ['Architecture', 'Architectural Engineering', 'Interior Design'],
            'survey'   => ['Surveying', 'Geotechnical Engineering', 'Civil Engineering'],
            'environment' => ['Environmental Science', 'Environmental Engineering', 'Ecology', 'Environmental Law', 'Marine Biology'],
            'بيئة'    => ['Environmental Science', 'Environmental Engineering', 'Ecology'],
            'psychiatry' => ['Psychiatry', 'Psychology', 'Neuroscience'],
            'neurology' => ['Neuroscience', 'Psychiatry', 'Biology', 'Anatomy'],
            'pediatrics' => ['Pediatrics', 'Medicine', 'Child Care'],
            'اطفال'   => ['Pediatrics', 'Early Childhood Education'],
            'nutrition' => ['Nutrition', 'Dietetics', 'Food Science', 'Health Administration'],
            'تغذية'   => ['Nutrition', 'Dietetics', 'Food Science'],
            'public health' => ['Public Health', 'Epidemiology', 'Environmental Health', 'Health Administration'],
            'صحة'     => ['Public Health', 'Epidemiology', 'Nutrition'],
            'pharmacology' => ['Pharmacology', 'Pharmacy', 'Medicine', 'Chemistry'],
            'veterinary' => ['Veterinary Medicine', 'Zoology', 'Biology'],
            'بيطري'   => ['Veterinary Medicine', 'Zoology'],
            'lawyer'   => ['Law', 'Business Law', 'Company Law', 'Criminal Law', 'Civil Law'],
            'محاماة'  => ['Law', 'Company Law', 'Criminal Law', 'Civil Law'],
            'accountant' => ['Accountancy', 'Auditing', 'Income Tax', 'Financial Management'],
            'محاسبة'  => ['Accountancy', 'Auditing', 'Financial Management', 'Income Tax'],
            'doctor'   => ['Medicine', 'Surgery', 'Internal Medicine', 'Pediatrics', 'Cardiology'],
            'طبيب'    => ['Medicine', 'Surgery', 'Internal Medicine', 'Anatomy', 'Physiology'],
            'engineer' => ['Engineering Mechanics', 'Civil Engineering', 'Electrical Engineering', 'Mechanical', 'Software Engineering'],
            'مهندس'   => ['Engineering Mechanics', 'Civil Engineering', 'Electrical Engineering', 'Mechanical'],
            'teacher'  => ['Education', 'Teaching Methods', 'Educational Psychology'],
            'مدرس'    => ['Education', 'Teaching Methods', 'Curriculum Development'],
            'student'  => ['Education', 'Educational Psychology', 'Special Education'],
            'exam'     => ['Exam Help', 'IELTS', 'Income Tax', 'All exam prep subjects'],
            'اختبار'  => ['IELTS', 'Income Tax'],
            'homework' => ['Assignment Help', 'Academic Writing', 'Programming', 'All subjects'],
            'assignment' => ['Assignment Help', 'Academic Writing'],
            'research' => ['Academic Writing', 'Research Methods', 'Data Science', 'Statistics'],
            'بحث'     => ['Academic Writing', 'Research Methods'],
            'project'  => ['Project Help', 'Programming', 'Engineering Mechanics', 'All project subjects'],
            'مشروع'   => ['Project Help', 'Programming', 'Engineering Mechanics'],
            'ielts'    => ['IELTS', 'English', 'Communication Skills'],
            'toefl'    => ['English', 'IELTS', 'Communication Skills'],
            'quran'    => ['Islamic Education', 'Arabic', 'Arabic Literature'],
            'قرآن'    => ['Islamic Education', 'Arabic'],
            'sports'   => ['Physical Education', 'Sports Science', 'Coaching', 'Sports Management'],
            'coaching' => ['Coaching', 'Sports Science', 'Physical Education'],
            'swimming' => ['Physical Education', 'Sports Science'],
            'chess'    => ['Educational Activities', 'Psychology', 'Algorithm & Data Structures'],
            'شطرنج'   => ['Educational Activities', 'Algorithm & Data Structures'],
            'photography' => ['Photography', 'Art and Craft', 'Digital Media'],
            'تصوير'   => ['Photography', 'Film Studies', 'Digital Media'],
            'video'    => ['Film Studies', 'Digital Media', 'Photography'],
            'writing'  => ['Creative Writing', 'Academic Writing', 'Arabic Literature', 'English Literature', 'Journalism'],
            'كتابة'   => ['Creative Writing', 'Academic Writing', 'Arabic Literature'],
            'reading'  => ['Arabic', 'English', 'Arabic Literature', 'English Literature', 'Early Childhood Education'],
            'قراءة'   => ['Arabic', 'Arabic Literature', 'Early Childhood Education'],
            'geology'  => ['Geology', 'Earth Science', 'Paleontology', 'Geography'],
            'psychology' => ['Psychology', 'Psychology and Sociology', 'Psychiatry', 'Organizational Behavior'],
            'social'   => ['Social Studies', 'Sociology', 'Social Work', 'Political Science'],
            'اجتماع'  => ['Social Studies', 'Sociology', 'Social Work'],
            'political' => ['Political Science', 'International Relations', 'Law', 'Public Administration'],
            'سياسة'   => ['Political Science', 'International Relations', 'Law'],
        ];

        $count = 0;
        foreach ($map as $term => $subjectNames) {
            foreach ($subjectNames as $name) {
                $subject = Subject::where('name', $name)->first();
                if (!$subject) {
                    continue; // skip if subject doesn't exist in DB
                }
                SubjectSearchTerm::firstOrCreate([
                    'subject_id' => $subject->id,
                    'term' => $term,
                ]);
                $count++;
            }
        }

        $this->command->info("Inserted {$count} search term mappings.");
    }
}
